// NOTE: PAGE_HTML is built with string concatenation (not a template literal)
// on purpose -- the embedded <script> below is plain JS with its own quotes,
// and keeping the outer wrapper a template literal would risk collisions.

var HEAD =
  '<!doctype html>\n' +
  '<html lang="en">\n' +
  '<head>\n' +
  '<meta charset="UTF-8" />\n' +
  '<meta name="viewport" content="width=device-width, initial-scale=1" />\n' +
  '<title>Just a Chit-Chat</title>\n' +
  '<link rel="preconnect" href="https://fonts.googleapis.com">\n' +
  '<link href="https://fonts.googleapis.com/css2?family=Baloo+2:wght@500;600;700;800&family=Nunito:wght@400;600;700;800&display=swap" rel="stylesheet">\n' +
  '<style>\n' +
  ':root{\n' +
  '  --bg:#f4f7ef;\n' +
  '  --panel:#ffffff;\n' +
  '  --ink:#1f3329;\n' +
  '  --muted:#5c7364;\n' +
  '  --line:#dbe6d6;\n' +
  '  --forest:#1f5c46;\n' +
  '  --forest-dark:#153f30;\n' +
  '  --leaf:#3f8f5f;\n' +
  '  --bark:#7a5230;\n' +
  '  --gold:#e8a838;\n' +
  '  --gold-dark:#c8871d;\n' +
  '  --sky:#e4f0ea;\n' +
  '  --berry:#c14444;\n' +
  '  --radius:16px;\n' +
  '  --shadow:0 10px 30px rgba(21,63,48,0.12);\n' +
  '}\n' +
  '*{box-sizing:border-box;}\n' +
  'html,body{margin:0;padding:0;}\n' +
  'body{\n' +
  '  background:var(--bg);\n' +
  '  background-image:radial-gradient(circle at 10% 0%, #eef4e6 0%, var(--bg) 55%);\n' +
  '  color:var(--ink);\n' +
  '  font-family:"Nunito",sans-serif;\n' +
  '  min-height:100vh;\n' +
  '}\n' +
  'h1,h2,h3,.display{font-family:"Baloo 2",cursive;}\n' +
  '#app{max-width:960px;margin:0 auto;padding:24px 18px 60px;}\n' +
  '.topbar{display:flex;align-items:center;justify-content:space-between;margin-bottom:20px;}\n' +
  '.brand{display:flex;align-items:center;gap:10px;}\n' +
  '.brand-mark{font-size:28px;}\n' +
  '.brand h1{font-size:22px;margin:0;color:var(--forest-dark);}\n' +
  '.brand span{display:block;font-size:12px;color:var(--muted);font-weight:700;letter-spacing:.04em;}\n' +
  '.pill{background:var(--panel);border:1px solid var(--line);border-radius:999px;padding:6px 14px;font-weight:800;font-size:13px;color:var(--forest-dark);box-shadow:var(--shadow);}\n' +
  '.card{background:var(--panel);border-radius:var(--radius);box-shadow:var(--shadow);border:1px solid var(--line);padding:22px;}\n' +
  '.stack{display:flex;flex-direction:column;gap:16px;}\n' +
  '.row{display:flex;gap:14px;flex-wrap:wrap;}\n' +
  'button{font-family:"Nunito",sans-serif;font-weight:800;cursor:pointer;border:none;border-radius:12px;padding:12px 20px;font-size:15px;transition:transform .08s ease, box-shadow .15s ease;}\n' +
  'button:active{transform:translateY(1px) scale(0.99);}\n' +
  '.btn-primary{background:var(--forest);color:#fff;box-shadow:0 6px 0 var(--forest-dark);}\n' +
  '.btn-primary:hover{background:var(--forest-dark);}\n' +
  '.btn-gold{background:var(--gold);color:#3a2705;box-shadow:0 6px 0 var(--gold-dark);}\n' +
  '.btn-ghost{background:transparent;color:var(--forest-dark);border:2px solid var(--line);box-shadow:none;}\n' +
  '.btn-danger{background:#fff;color:var(--berry);border:2px solid var(--berry);box-shadow:none;padding:8px 14px;font-size:13px;}\n' +
  '.btn-small{padding:8px 14px;font-size:13px;box-shadow:none;}\n' +
  'input[type=text],input[type=password],textarea,select{\n' +
  '  width:100%;font-family:"Nunito",sans-serif;font-size:15px;padding:12px 14px;border-radius:10px;\n' +
  '  border:2px solid var(--line);background:#fbfdf9;color:var(--ink);\n' +
  '}\n' +
  'textarea{min-height:70px;resize:vertical;}\n' +
  'input:focus,textarea:focus,select:focus{outline:3px solid var(--gold);border-color:var(--gold-dark);}\n' +
  'label{font-weight:800;font-size:13px;color:var(--forest-dark);display:block;margin-bottom:6px;}\n' +
  '.hint{color:var(--muted);font-size:12px;margin-top:4px;}\n' +
  '.center{display:flex;flex-direction:column;align-items:center;justify-content:center;min-height:70vh;text-align:center;}\n' +
  '.logo-big{font-size:56px;margin-bottom:6px;}\n' +
  '.login-card{max-width:420px;width:100%;}\n' +
  '.topic-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(220px,1fr));gap:14px;}\n' +
  '.topic-card{cursor:pointer;border-radius:var(--radius);overflow:hidden;background:var(--panel);border:1px solid var(--line);box-shadow:var(--shadow);transition:transform .12s ease;}\n' +
  '.topic-card:hover{transform:translateY(-3px);}\n' +
  '.topic-card img{width:100%;height:120px;object-fit:cover;display:block;background:var(--sky);}\n' +
  '.topic-card .tc-body{padding:12px 14px;}\n' +
  '.topic-card h3{font-size:16px;margin:0 0 4px;color:var(--forest-dark);}\n' +
  '.tag{display:inline-block;background:var(--sky);color:var(--forest-dark);font-size:11px;font-weight:800;padding:3px 8px;border-radius:999px;margin-right:4px;}\n' +
  '.tabs{display:flex;gap:8px;margin-bottom:16px;flex-wrap:wrap;}\n' +
  '.tab{padding:9px 16px;border-radius:999px;background:var(--panel);border:1px solid var(--line);font-weight:800;cursor:pointer;font-size:13px;color:var(--muted);}\n' +
  '.tab.active{background:var(--forest);color:#fff;border-color:var(--forest);}\n' +
  '.tree-wrap{display:flex;align-items:center;justify-content:center;gap:6px;margin:10px 0 22px;flex-wrap:wrap;}\n' +
  '.leaf{width:44px;height:44px;border-radius:50% 50% 50% 4px;background:var(--line);color:#fff;display:flex;align-items:center;justify-content:center;font-weight:800;font-family:"Baloo 2",cursive;font-size:16px;border:2px solid #cfe0c8;transition:all .25s ease;}\n' +
  '.leaf.done{background:var(--leaf);border-color:var(--forest);box-shadow:0 4px 0 var(--forest-dark);}\n' +
  '.leaf-label{font-size:10px;text-align:center;color:var(--muted);font-weight:800;width:44px;}\n' +
  '.branch{width:24px;height:3px;background:var(--bark);border-radius:2px;}\n' +
  '.part-block{border:2px dashed var(--line);border-radius:12px;padding:14px;background:#fbfdf9;}\n' +
  '.part-block.emphasis{border-color:var(--gold-dark);background:#fffaf0;box-shadow:0 0 0 3px rgba(232,168,56,0.15);}\n' +
  '.part-block.filled{border-style:solid;border-color:var(--leaf);background:#f2fbf4;}\n' +
  '.starter{font-size:12px;color:var(--muted);font-style:italic;margin-bottom:6px;}\n' +
  '.score-badge{display:inline-flex;align-items:center;gap:8px;background:var(--gold);color:#3a2705;font-weight:800;padding:10px 18px;border-radius:999px;font-size:20px;box-shadow:0 6px 0 var(--gold-dark);}\n' +
  '.feedback-box{background:var(--sky);border-radius:12px;padding:14px 16px;border:1px solid #cfe3d4;}\n' +
  '.breakdown-row{display:flex;justify-content:space-between;align-items:center;padding:8px 0;border-bottom:1px dashed var(--line);}\n' +
  '.breakdown-row:last-child{border-bottom:none;}\n' +
  '.board-row{display:flex;justify-content:space-between;align-items:center;padding:10px 14px;border-radius:10px;}\n' +
  '.board-row:nth-child(odd){background:#f7faf4;}\n' +
  '.rank{font-family:"Baloo 2",cursive;font-weight:800;width:28px;color:var(--forest-dark);}\n' +
  '.warn{background:#fff4e9;border:1px solid #f0d3a8;color:#7a4a09;padding:10px 14px;border-radius:10px;font-size:13px;font-weight:700;}\n' +
  '.error{background:#fdecec;border:1px solid #f2b8b8;color:var(--berry);padding:10px 14px;border-radius:10px;font-size:13px;font-weight:700;}\n' +
  '.small{font-size:12px;color:var(--muted);}\n' +
  '.flex-between{display:flex;justify-content:space-between;align-items:center;flex-wrap:wrap;gap:8px;}\n' +
  '.teacher-table{width:100%;border-collapse:collapse;}\n' +
  '.teacher-table th{text-align:left;font-size:12px;color:var(--muted);padding:6px 8px;border-bottom:2px solid var(--line);}\n' +
  '.teacher-table td{padding:8px;border-bottom:1px solid var(--line);font-size:13px;vertical-align:top;}\n' +
  '.footer-note{margin-top:30px;text-align:center;font-size:12px;color:var(--muted);}\n' +
  '.coach-panel{background:#fff8ec;border:2px dashed var(--gold-dark);border-radius:12px;padding:14px 16px;margin:2px 0;}\n' +
  '.coach-starters{margin:0;padding-left:20px;}\n' +
  '.coach-starters li{margin-bottom:4px;font-size:14px;}\n' +
  '.coach-resource{margin-top:6px;font-size:14px;}\n' +
  '.coach-resource a{color:var(--forest-dark);font-weight:700;}\n' +
  '.locked-video-wrap{position:relative;width:100%;aspect-ratio:16/9;border-radius:10px;overflow:hidden;background:#000;margin-top:4px;}\n' +
  '.locked-video-frame{width:100%;height:100%;}\n' +
  '.locked-video-cover{position:absolute;inset:0;background:rgba(21,63,48,0.85);display:flex;align-items:center;justify-content:center;}\n' +
  '.coach-field-group{border:1px solid var(--line);border-radius:10px;padding:12px;background:#fbfdf9;}\n' +
  '@media (max-width:640px){ #app{padding:16px 10px 50px;} }\n' +
  '</style>\n' +
  '</head>\n';

var BODY_OPEN =
  '<body>\n' +
  '<div id="app"></div>\n' +
  '<script>\n';

var APP_JS = [
"var API = '';",
"var state = { token: null, role: null, name: null, pupilClass: null, teacherPupilView: null, screen: 'login', topics: [], currentTopic: null, framework: 'TREES', leaderboard: [], teacherTab: 'leaderboard', teacherSubs: [], subsOffset: 0, subsTotal: 0, subsHasMore: false, subsLoading: false, lastResult: null, pendingTeacherLogin: false, pendingTeacherUsername: '', error: '', pupilTab: 'play', practiceMode: false, responseMode: 'trees', rubricText: '', rubricIsDefault: true, groqModel: '', groqModelIsDefault: true, groqModelOptions: [], recording: null, coachOpen: [false,false,false], coachUsed: [false,false,false], pupilsList: null, isSuperAdmin: false, assignedClasses: [], classesList: [], subsFilterClass: '', subsFilterTopic: '', subsSort: 'newest', subsArchivedView: 'active', selectedSubs: {}, lbFilterClass: '', pupilsFilterClass: '', adminTeachers: null, editingTeacherAdmin: null };",
"",
"function qs(sel){ return document.querySelector(sel); }",
"function el(html){ var d=document.createElement('div'); d.innerHTML=html; return d.firstElementChild; }",
"function esc(s){ if(s===undefined||s===null) return ''; return String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/\"/g,'&quot;'); }",
"",
"function authHeaders(){",
"  var h = {'content-type':'application/json'};",
"  if(state.token) h['authorization'] = 'Bearer ' + state.token;",
"  return h;",
"}",
"",
"function apiGet(path){",
"  return fetch(API+path, { headers: authHeaders() }).then(function(r){ return r.json().then(function(d){ return {ok:r.ok, data:d}; }); });",
"}",
"function apiSend(path, method, body){",
"  return fetch(API+path, { method: method, headers: authHeaders(), body: JSON.stringify(body||{}) }).then(function(r){ return r.json().then(function(d){ return {ok:r.ok, data:d}; }); });",
"}",
"",
"function render(){",
"  var app = qs('#app');",
"  destroyAllLockedPlayers();",
"  var html = '';",
"  html += topbarHtml();",
"  if(state.error){ html += '<div class=\"error\" style=\"margin-bottom:14px;\">' + esc(state.error) + '</div>'; }",
"  if(state.screen === 'login'){ html += loginHtml(); }",
"  else if(state.screen === 'pupil'){ html += pupilHtml(); }",
"  else if(state.screen === 'teacher'){ html += teacherHtml(); }",
"  html += '<div class=\"footer-note\">Just a Chit-Chat &middot; practise the TREES framework for oral conversation</div>';",
"  app.innerHTML = html;",
"  initLockedVideos();",
"}",
"",
"function topbarHtml(){",
"  var right = '';",
"  if(state.role){",
"    right = '<div class=\"row\" style=\"align-items:center;\">' +",
"      '<span class=\"pill\">' + (state.role==='teacher' ? ('Teacher Tools' + (state.isSuperAdmin ? ' (Admin)' : (state.assignedClasses&&state.assignedClasses.length ? ' ('+esc(state.assignedClasses.join(', '))+')' : ''))) : esc(state.name) + (state.pupilClass && state.pupilClass!=='unassigned' ? ' ('+esc(state.pupilClass)+')' : '')) + '</span>' +",
"      '<button class=\"btn-ghost btn-small\" data-action=\"logout\">Log out</button>' +",
"      '</div>';",
"  }",
"  return '<div class=\"topbar\">' +",
"    '<div class=\"brand\"><span class=\"brand-mark\">&#128172;</span><div><h1>Just a Chit-Chat</h1><span>PRACTISE ORAL CONVERSATION WITH TREES</span></div></div>' +",
"    right +",
"    '</div>';",
"}"
];

var LOGIN_JS = [
"function loginHtml(){",
"  if(state.pendingTeacherLogin){",
"    return '<div class=\"center\">' +",
"      '<div class=\"card login-card stack\">' +",
"      '<div class=\"logo-big\">&#128274;</div>' +",
"      '<h2 style=\"margin:0;\">Teacher Tools</h2>' +",
"      '<p class=\"small\">Enter the teacher password to access the leaderboard, submissions and topic editor.</p>' +",
"      '<div><label>Password</label><input type=\"password\" id=\"teacherPassword\" placeholder=\"Password\"/></div>' +",
"      '<div class=\"row\">' +",
"      '<button class=\"btn-primary\" data-action=\"teacher-login\">Enter</button>' +",
"      '<button class=\"btn-ghost\" data-action=\"cancel-teacher\">Back</button>' +",
"      '</div></div></div>';",
"  }",
"  return '<div class=\"center\">' +",
"    '<div class=\"card login-card stack\">' +",
"    '<div class=\"logo-big\">&#128172;</div>' +",
"    '<h2 style=\"margin:0;\">Ready for a chit-chat?</h2>' +",
"    '<p class=\"small\">Enter your name to start practising with TREES &mdash; worth 20 marks for content, plus 5 marks for Language Use (25 total).</p>' +",
"    '<div><label>Your Name</label><input type=\"text\" id=\"loginName\" placeholder=\"e.g. Ashraf or Ashraf&#64;5IG\" maxlength=\"60\"/><div class=\"hint\">Add your class with an &#64; sign (e.g. Jovan&#64;5IG) so your teacher can track your progress by class. This is optional.</div></div>' +",
"    '<button class=\"btn-primary\" data-action=\"login\">Start Quest</button>' +",
"    '</div></div>';",
"}",
"",
"function doLogin(){",
"  var nameInput = qs('#loginName');",
"  var name = nameInput ? nameInput.value.trim() : '';",
"  if(!name){ state.error='Please enter a name.'; render(); return; }",
"  apiSend('/api/login','POST',{name:name}).then(function(res){",
"    if(!res.ok){ state.error = res.data.error || 'Login failed.'; render(); return; }",
"    if(res.data.requiresTeacherPassword){",
"      state.pendingTeacherLogin = true; state.pendingTeacherUsername = res.data.username || name.toLowerCase(); state.error=''; render(); return;",
"    }",
"    state.token = res.data.token; state.role='pupil'; state.name=res.data.name; state.pupilClass=res.data.pupilClass; state.screen='pupil'; state.error='';",
"    loadTopics(); loadLeaderboard();",
"    render();",
"  });",
"}",
"",
"function doTeacherLogin(){",
"  var pw = qs('#teacherPassword') ? qs('#teacherPassword').value : '';",
"  apiSend('/api/teacher/login','POST',{username: state.pendingTeacherUsername || 'palpatine', password: pw}).then(function(res){",
"    if(!res.ok){ state.error = res.data.error || 'Login failed.'; render(); return; }",
"    state.token = res.data.token; state.role='teacher'; state.name=res.data.name||'Teacher'; state.screen='teacher'; state.error=''; state.pendingTeacherLogin=false;",
"    state.isSuperAdmin = !!res.data.isSuperAdmin; state.assignedClasses = res.data.assignedClasses || [];",
"    if(!state.isSuperAdmin && ['topics','settings','admins'].indexOf(state.teacherTab)!==-1) state.teacherTab='leaderboard';",
"    loadTopics(); loadTeacherSubmissions(true); loadLeaderboard(); loadTeacherClasses();",
"    render();",
"  });",
"}",
"",
"function doLogout(){",
"  state = { token:null, role:null, name:null, pupilClass:null, teacherPupilView:null, screen:'login', topics:[], currentTopic:null, framework:'TREES', leaderboard:[], teacherTab:'leaderboard', teacherSubs:[], subsOffset:0, subsTotal:0, subsHasMore:false, subsLoading:false, lastResult:null, pendingTeacherLogin:false, pendingTeacherUsername:'', error:'', pupilTab:'play', practiceMode:false, responseMode:'trees', rubricText:'', rubricIsDefault:true, groqModel:'', groqModelIsDefault:true, groqModelOptions:[], recording:null, coachOpen:[false,false,false], coachUsed:[false,false,false], pupilsList:null, isSuperAdmin:false, assignedClasses:[], classesList:[], subsFilterClass:'', subsFilterTopic:'', subsSort:'newest', subsArchivedView:'active', selectedSubs:{}, lbFilterClass:'', pupilsFilterClass:'', adminTeachers:null, editingTeacherAdmin:null };",
"  render();",
"}"
];

var PUPIL_JS = [
"var recognitionInstance = null;",
"function speechSupported(){ return !!(window.SpeechRecognition || window.webkitSpeechRecognition); }",
"function micButtonHtml(targetId){",
"  if(!speechSupported()) return '';",
"  return '<button type=\"button\" class=\"btn-ghost btn-small\" data-action=\"toggle-record\" data-target=\"'+targetId+'\" id=\"micBtn_'+targetId+'\" style=\"margin-top:6px;\">&#127908; Record instead</button>';",
"}",
"function setMicButtonState(targetId, active){",
"  var btn = document.getElementById('micBtn_'+targetId);",
"  if(btn) btn.innerHTML = active ? '&#9209;&#65039; Stop recording' : '&#127908; Record instead';",
"}",
"function stopRecording(){",
"  if(recognitionInstance){ try{ recognitionInstance.stop(); }catch(e){} }",
"  var prev = state.recording;",
"  recognitionInstance = null;",
"  state.recording = null;",
"  if(prev) setMicButtonState(prev, false);",
"}",
"function startRecording(targetId){",
"  stopRecording();",
"  var Recognition = window.SpeechRecognition || window.webkitSpeechRecognition;",
"  if(!Recognition) return;",
"  var recog = new Recognition();",
"  recog.continuous = true;",
"  recog.interimResults = false;",
"  recog.lang = 'en-SG';",
"  recog.onresult = function(event){",
"    var textarea = document.getElementById(targetId);",
"    if(!textarea) return;",
"    var finalChunk = '';",
"    for(var i=event.resultIndex; i<event.results.length; i++){",
"      if(event.results[i].isFinal) finalChunk += event.results[i][0].transcript + ' ';",
"    }",
"    if(finalChunk){",
"      var current = textarea.value;",
"      if(current && !/\\s$/.test(current)) current += ' ';",
"      textarea.value = current + finalChunk;",
"      textarea.dispatchEvent(new Event('input', {bubbles:true}));",
"    }",
"  };",
"  recog.onerror = function(){ stopRecording(); };",
"  recog.onend = function(){ if(state.recording===targetId) stopRecording(); };",
"  recognitionInstance = recog;",
"  state.recording = targetId;",
"  setMicButtonState(targetId, true);",
"  try{ recog.start(); }catch(e){ stopRecording(); }",
"}",
"",
"function coachUsedTag(used){",
"  if(!used) return '';",
"  return '<span class=\"tag\" style=\"background:#fff4e9;color:#8a5a12;\">Coach used</span>';",
"}",
"function aiStatusTag(markedBy){",
"  if(markedBy==='fallback') return '<span class=\"tag\" style=\"background:#fdecec;color:#b23a3a;\">AI unavailable; scores may be more generous than they should be</span>';",
"  return '<span class=\"tag\" style=\"background:#eaf7ec;color:#1f7a3d;\">AI connected</span>';",
"}",
"",
"// ---------- NPC Coach: sentence starters + teacher-set resources ----------",
"// Video resources use the YouTube IFrame API (loaded lazily, only once a",
"// video resource is actually rendered) with rel=0/modestbranding so the",
"// player never surfaces other channels' suggested videos, and a custom cover",
"// takes over on end instead of YouTube's own end-screen grid - the pupil",
"// only ever sees the teacher-picked video, never a path to another one.",
"var ytApiRequested = false;",
"var lockedPlayers = {};",
"function ensureYoutubeApi(){",
"  if(ytApiRequested) return;",
"  ytApiRequested = true;",
"  window.onYouTubeIframeAPIReady = function(){ initLockedVideos(); };",
"  var tag = document.createElement('script');",
"  tag.src = 'https://www.youtube.com/iframe_api';",
"  document.head.appendChild(tag);",
"}",
"function destroyAllLockedPlayers(){",
"  Object.keys(lockedPlayers).forEach(function(id){",
"    try{ lockedPlayers[id].destroy(); }catch(e){}",
"  });",
"  lockedPlayers = {};",
"}",
"function initLockedVideos(){",
"  var frames = document.querySelectorAll('.locked-video-frame[data-yt-id]');",
"  if(!frames.length) return;",
"  if(typeof YT === 'undefined' || !YT.Player){ ensureYoutubeApi(); return; }",
"  frames.forEach(function(el){",
"    if(lockedPlayers[el.id]) return;",
"    var videoId = el.getAttribute('data-yt-id');",
"    lockedPlayers[el.id] = new YT.Player(el.id, {",
"      videoId: videoId,",
"      playerVars: { rel: 0, modestbranding: 1, iv_load_policy: 3, fs: 1, origin: window.location.origin },",
"      events: {",
"        onStateChange: function(ev){",
"          if(YT && ev.data === YT.PlayerState.ENDED){",
"            var wrap = document.getElementById('wrap_'+el.id);",
"            if(wrap && !wrap.querySelector('.locked-video-cover')){",
"              var cover = document.createElement('div');",
"              cover.className = 'locked-video-cover';",
"              cover.innerHTML = '<button class=\"btn-gold btn-small\" type=\"button\">&#9654; Watch Again</button>';",
"              cover.querySelector('button').onclick = function(){",
"                cover.remove();",
"                ev.target.seekTo(0);",
"                ev.target.playVideo();",
"              };",
"              wrap.appendChild(cover);",
"            }",
"          }",
"        }",
"      }",
"    });",
"  });",
"}",
"function extractYoutubeId(url){",
"  if(!url) return null;",
"  var m = String(url).match(/(?:youtube\\.com\\/(?:watch\\?v=|shorts\\/|embed\\/)|youtu\\.be\\/)([a-zA-Z0-9_-]{11})/);",
"  return m ? m[1] : null;",
"}",
"function resourceItemHtml(res, idx, roundIdx){",
"  if(res.type==='video'){",
"    var ytId = extractYoutubeId(res.url);",
"    if(ytId){",
"      ensureYoutubeApi();",
"      var playerId = 'ytplayer_r'+roundIdx+'_'+idx;",
"      return '<div class=\"coach-resource\">' +",
"        '<div class=\"small\" style=\"font-weight:800;margin-bottom:6px;\">&#9654; '+esc(res.title)+'</div>' +",
"        '<div class=\"locked-video-wrap\" id=\"wrap_'+playerId+'\">' +",
"        '<div id=\"'+playerId+'\" class=\"locked-video-frame\" data-yt-id=\"'+esc(ytId)+'\"></div>' +",
"        '</div></div>';",
"    }",
"    return '<div class=\"coach-resource\"><a href=\"'+esc(res.url)+'\" target=\"_blank\" rel=\"noopener noreferrer\">&#9654; '+esc(res.title)+' (opens in new tab)</a></div>';",
"  }",
"  return '<div class=\"coach-resource\"><a href=\"'+esc(res.url)+'\" target=\"_blank\" rel=\"noopener noreferrer\">&#128218; '+esc(res.title)+' (opens in new tab)</a></div>';",
"}",
"function coachHasContent(i){",
"  var t = state.currentTopic;",
"  var c = (t && t.coach && t.coach[i]) || {};",
"  return (c.starters && c.starters.length>0) || (c.resources && c.resources.length>0);",
"}",
"function coachButtonHtml(i){",
"  if(!coachHasContent(i)) return '';",
"  var label = state.coachOpen[i] ? 'Hide Coach' : '&#129302; Ask the Coach';",
"  return '<button class=\"btn-ghost btn-small\" data-action=\"toggle-coach\" data-round=\"'+i+'\">'+label+'</button>';",
"}",
"function coachPanelHtml(i){",
"  if(!state.coachOpen[i]) return '';",
"  var t = state.currentTopic;",
"  var c = (t && t.coach && t.coach[i]) || {starters:[], resources:[]};",
"  var startersHtml = (c.starters||[]).map(function(s){ return '<li>'+esc(s)+'</li>'; }).join('');",
"  var resourcesHtml = (c.resources||[]).map(function(r,idx){ return resourceItemHtml(r, idx, i); }).join('');",
"  var startersBlock = startersHtml ? '<div><div class=\"small\" style=\"font-weight:800;margin-bottom:4px;\">Sentence starters</div><ul class=\"coach-starters\">'+startersHtml+'</ul></div>' : '';",
"  var resourcesBlock = resourcesHtml ? '<div style=\"margin-top:10px;\">'+resourcesHtml+'</div>' : '';",
"  return '<div class=\"coach-panel\">'+startersBlock+resourcesBlock+'</div>';",
"}",
"var TREES_PARTS = [",
"  {key:'T', label:'Thought', max:2, starter:'I think that... / In my opinion...'},",
"  {key:'R', label:'Reason', max:2, starter:'This is because... / One reason is...'},",
"  {key:'E1', label:'Evidence', max:2, starter:'In the picture, I can see...'},",
"  {key:'E2', label:'Experience', max:12, starter:'The most important part! Try to include: WHO was there, WHAT happened, WHEN and WHERE it happened, WHY it happened (or why you acted), HOW it ended, and how you felt or what you learnt.'},",
"  {key:'S', label:'Suggestion', max:2, starter:'I suggest that... / In future, we can...'}",
"];",
"function loadTopics(){",
"  apiGet('/api/topics').then(function(res){",
"    if(res.ok){ state.topics = res.data.topics; render(); }",
"  });",
"}",
"function loadLeaderboard(){",
"  var q = (state.role==='teacher' && state.lbFilterClass) ? ('?class='+encodeURIComponent(state.lbFilterClass)) : '';",
"  apiGet('/api/leaderboard'+q).then(function(res){",
"    if(res.ok){ state.leaderboard = res.data.leaderboard; if(state.screen!=='login') render(); }",
"  });",
"}",
"",
"function pupilHtml(){",
"  var html = '<div class=\"tabs\">' +",
"    tabBtn('play','Play') + tabBtn('leaderboard','Leaderboard') + '</div>';",
"  if(state.pupilTab === 'leaderboard'){ html += leaderboardHtml(); return html; }",
"  if(state.lastResult){ html += resultHtml(); return html; }",
"  if(state.currentTopic){ html += builderHtml(); return html; }",
"  html += topicGridHtml();",
"  return html;",
"}",
"",
"function tabBtn(id,label){",
"  var active = state.pupilTab===id ? ' active' : '';",
"  return '<div class=\"tab'+active+'\" data-action=\"pupil-tab\" data-tab=\"'+id+'\">'+esc(label)+'</div>';",
"}",
"",
"function topicGridHtml(){",
"  var cards = state.topics.map(function(t){",
"    var tags = (t.tags||[]).map(function(tg){ return '<span class=\"tag\">'+esc(tg)+'</span>'; }).join('');",
"    var img = t.imageUrl ? '<img src=\"'+esc(t.imageUrl)+'\" alt=\"\"/>' : '<div style=\"height:120px;background:var(--sky);\"></div>';",
"    return '<div class=\"topic-card\" data-action=\"pick-topic\" data-id=\"'+esc(t.id)+'\">'+img+",
"      '<div class=\"tc-body\"><h3>'+esc(t.title)+'</h3>'+tags+'</div></div>';",
"  }).join('');",
"  return '<h2>Choose a Topic Card</h2><p class=\"small\">Each topic has 3 questions. You'+\"'\"+'ll answer all 3 in one sitting, and your final score is the average of the three.</p><div class=\"topic-grid\">'+cards+'</div>';",
"}",
"",
"function currentParts(){ return TREES_PARTS; }",
"function qsVal(id){ var e = document.getElementById(id); return e ? e.value : ''; }",
"function sessionQuestions(){",
"  var t = state.currentTopic;",
"  var qs = (t && t.questions) ? t.questions.slice(0,3) : [];",
"  while(qs.length < 3) qs.push('Tell me more about this topic.');",
"  return qs;",
"}",
"",
"function roundTreeProgressHtml(i){",
"  var pieces = currentParts().map(function(p,idx){",
"    var val = qsVal('r'+i+'_'+p.key);",
"    var filled = val && val.trim().length>0;",
"    var leaf = '<div class=\"leaf'+(filled?' done':'')+'\">'+p.key.charAt(0)+'</div>';",
"    var lab = '<div class=\"leaf-label\">'+esc(p.label)+'</div>';",
"    var col = '<div style=\"display:flex;flex-direction:column;align-items:center;gap:4px;\">'+leaf+lab+'</div>';",
"    if(idx===0) return col;",
"    return '<div class=\"branch\"></div>'+col;",
"  }).join('');",
"  return '<div class=\"tree-wrap\">'+pieces+'</div>';",
"}",
"",
"function modeToggleHtml(){",
"  var treesActive = state.responseMode!=='single';",
"  return '<div class=\"row\" style=\"margin-bottom:4px;\">' +",
"    '<button class=\"'+(treesActive?'btn-primary':'btn-ghost')+' btn-small\" data-action=\"set-mode\" data-mode=\"trees\">Separated TREES branches</button>' +",
"    '<button class=\"'+(!treesActive?'btn-primary':'btn-ghost')+' btn-small\" data-action=\"set-mode\" data-mode=\"single\">Single response box</button>' +",
"    '</div>' +",
"    '<p class=\"small\">'+(treesActive ? 'Fill in each branch separately - great for beginners.' : 'Speak/write your whole answer in one go, just like the real exam - the AI will still mark it against every TREES branch.')+'</p>';",
"}",
"",
"function roundHtml(i, question){",
"  var mode = state.responseMode==='single' ? 'single' : 'trees';",
"  var body;",
"  if(mode==='trees'){",
"    var blocks = currentParts().map(function(p){",
"      var extra = p.key==='E2' ? ' emphasis' : '';",
"      return '<div class=\"part-block'+extra+'\" id=\"block_r'+i+'_'+p.key+'\">' +",
"        '<label>'+esc(p.key.charAt(0))+' &mdash; '+esc(p.label)+' <span class=\"tag\">'+p.max+' '+(p.max===1?'mark':'marks')+'</span></label>' +",
"        '<div class=\"starter\">'+esc(p.starter)+'</div>' +",
"        '<textarea id=\"r'+i+'_'+p.key+'\" data-action=\"part-input\" data-round=\"'+i+'\" placeholder=\"Type your '+esc(p.label)+' here...\"></textarea>' +",
"        micButtonHtml('r'+i+'_'+p.key) +",
"        '</div>';",
"    }).join('<div style=\"height:10px;\"></div>');",
"    body = '<div id=\"treeProgress'+i+'\">'+roundTreeProgressHtml(i)+'</div>' + blocks;",
"  } else {",
"    body = '<textarea id=\"r'+i+'_single\" data-action=\"single-input\" style=\"min-height:160px;\" placeholder=\"Answer the question above in one go. Try to naturally include your thought, your reason, something from the picture, a real personal experience (who/what/when/where/why/how), and a suggestion.\"></textarea>' +",
"      '<div>'+micButtonHtml('r'+i+'_single')+'</div>';",
"  }",
"  return '<div class=\"card stack\" style=\"margin-bottom:16px;\">' +",
"    '<div class=\"flex-between\"><h3 style=\"margin:0;\">Question '+(i+1)+' of 3</h3>'+coachButtonHtml(i)+'</div>' +",
"    '<p style=\"font-weight:800;color:var(--forest-dark);\">'+esc(question)+'</p>' +",
"    coachPanelHtml(i) +",
"    body +",
"    '</div>';",
"}",
"",
"function builderHtml(){",
"  var t = state.currentTopic;",
"  var questions = sessionQuestions();",
"  var img = t.imageUrl ? '<img src=\"'+esc(t.imageUrl)+'\" alt=\"\" style=\"width:100%;max-height:260px;object-fit:cover;border-radius:12px;margin-bottom:14px;\"/>' : '';",
"  var practiceToggle = '<div class=\"row\" style=\"align-items:center;background:var(--sky);padding:10px 14px;border-radius:10px;\">' +",
"    '<label style=\"display:flex;align-items:center;gap:8px;margin:0;cursor:pointer;\">' +",
"    '<input type=\"checkbox\" id=\"practiceToggle\" data-action=\"toggle-practice\"'+(state.practiceMode?' checked':'')+' style=\"width:18px;height:18px;\"/>' +",
"    'Practice mode &mdash; get feedback but don\\'t count this on the leaderboard' +",
"    '</label></div>';",
"  var rounds = questions.map(function(q,i){ return roundHtml(i,q); }).join('');",
"  return '<div class=\"stack\">' +",
"    '<div class=\"card stack\">' +",
"    '<div class=\"flex-between\"><h2 style=\"margin:0;\">'+esc(t.title)+'</h2>' +",
"    '<button class=\"btn-ghost btn-small\" data-action=\"back-to-topics\">&larr; Change Topic</button></div>' +",
"    img +",
"    '<p class=\"small\">3 questions, each marked out of 25 (20 for TREES content, 5 for Language Use - Experience is worth the most within TREES, 12 marks). Your final score is the average of all three.</p>' +",
"    modeToggleHtml() +",
"    practiceToggle +",
"    '</div>' +",
"    rounds +",
"    '<div class=\"card\"><div class=\"row\"><button class=\"btn-gold\" data-action=\"submit-response\">Submit All 3 Answers for Marking &#127942;</button></div></div>' +",
"    '</div>';",
"}",
"",
"function submitResponse(){",
"  var mode = state.responseMode==='single' ? 'single' : 'trees';",
"  var questions = sessionQuestions();",
"  var answers = [];",
"  var missing = [];",
"  for(var i=0;i<3;i++){",
"    if(mode==='trees'){",
"      var parts = {};",
"      var roundMissing = [];",
"      currentParts().forEach(function(p){",
"        var v = qsVal('r'+i+'_'+p.key);",
"        parts[p.key] = v;",
"        if(!v || !v.trim()) roundMissing.push(p.label);",
"      });",
"      if(roundMissing.length) missing.push('Question '+(i+1)+': '+roundMissing.join(', '));",
"      answers.push({parts:parts});",
"    } else {",
"      var text = qsVal('r'+i+'_single');",
"      if(!text || !text.trim()) missing.push('Question '+(i+1)+' is empty');",
"      answers.push({text:text});",
"    }",
"  }",
"  if(missing.length){",
"    state.error = 'Please complete: ' + missing.join(' | ');",
"    render(); return;",
"  }",
"  state.error='';",
"  var btn = document.querySelector('[data-action=\"submit-response\"]');",
"  if(btn){ btn.disabled = true; btn.textContent = 'Marking all 3 answers...'; }",
"  apiSend('/api/submit','POST',{ topicId: state.currentTopic.id, mode: mode, answers: answers, practice: state.practiceMode, coachUsed: state.coachUsed }).then(function(res){",
"    if(!res.ok){ state.error = res.data.error || 'Could not submit.'; render(); return; }",
"    state.lastResult = res.data.record;",
"    state.lastWarning = res.data.warning;",
"    if(!state.practiceMode) loadLeaderboard();",
"    render();",
"  });",
"}",
"",
"function breakdownHtml(breakdown){",
"  return (breakdown||[]).map(function(b){",
"    var sub = '';",
"    if(b.subBreakdown && b.subBreakdown.length){",
"      sub = '<div style=\"margin:2px 0 8px 14px;\">' + b.subBreakdown.map(function(sb){",
"        return '<div class=\"breakdown-row\" style=\"padding:4px 0;border-bottom:none;\"><span class=\"small\">'+esc(sb.label)+'</span><span class=\"small\">'+esc(String(sb.points))+' / '+esc(String(sb.max))+'</span></div>';",
"      }).join('') + '</div>';",
"    }",
"    return '<div class=\"breakdown-row\"><span>'+esc(b.part)+'</span><span>'+esc(String(b.points))+' / '+esc(String(b.max))+'</span></div>' +",
"      (b.note ? '<div class=\"small\" style=\"margin:-4px 0 6px;\">'+esc(b.note)+'</div>' : '') + sub;",
"  }).join('');",
"}",
"",
"function resultHtml(){",
"  var r = state.lastResult;",
"  var pct = Math.round((r.finalScore / (r.maxScore||1)) * 100);",
"  var warn = state.lastWarning ? '<div class=\"warn\">'+esc(state.lastWarning)+'</div>' : '';",
"  var practiceNote = r.practice ? '<div class=\"warn\">This was a practice attempt &mdash; it was NOT added to the leaderboard.</div>' : '';",
"  var roundCards = (r.rounds||[]).map(function(rd,i){",
"    var modelAnswerBlock = rd.modelAnswer ? '<div class=\"coach-panel\" style=\"margin-top:10px;\"><div class=\"small\" style=\"font-weight:800;margin-bottom:4px;\">&#10024; A stronger version of your answer</div><p class=\"small\" style=\"margin:0;\">'+esc(rd.modelAnswer)+'</p></div>' : '';",
"    return '<div class=\"card stack\" style=\"margin-top:14px;\">' +",
"      '<div class=\"flex-between\"><h3 style=\"margin:0;\">Question '+(i+1)+'</h3><span class=\"pill\">'+rd.score+' / '+rd.max+'</span></div>' +",
"      aiStatusTag(rd.markedBy) +",
"      '<p class=\"small\" style=\"font-weight:700;\">'+esc(rd.question)+'</p>' +",
"      '<div class=\"feedback-box\">'+esc(rd.feedback)+'</div>' +",
"      '<div>'+breakdownHtml(rd.breakdown)+'</div>' +",
"      modelAnswerBlock +",
"      '</div>';",
"  }).join('');",
"  return '<div class=\"stack\">' +",
"    '<div class=\"card\">' +",
"    '<div class=\"center\" style=\"min-height:auto;padding:10px 0;\">' +",
"    '<div class=\"logo-big\">'+(pct>=70?'&#127881;':'&#128172;')+'</div>' +",
"    '<div class=\"small\" style=\"margin-bottom:6px;font-weight:800;\">FINAL SCORE (average of 3 questions)</div>' +",
"    '<div class=\"score-badge\">'+r.finalScore+' / '+r.maxScore+' points</div>' +",
"    '</div>' +",
"    practiceNote + warn +",
"    '</div>' +",
"    roundCards +",
"    '<div class=\"card\"><div class=\"row\">' +",
"    '<button class=\"btn-primary\" data-action=\"play-again\">Try Another Topic</button>' +",
"    '<button class=\"btn-ghost\" data-action=\"pupil-tab-lb\">View Leaderboard</button>' +",
"    '</div></div>' +",
"    '</div>';",
"}",
"",
"function leaderboardHtml(){",
"  var rows = state.leaderboard.map(function(p,i){",
"    return '<div class=\"board-row\"><span class=\"rank\">#'+(i+1)+'</span>' +",
"      '<span style=\"flex:1;padding:0 10px;font-weight:700;\">'+esc(p.name)+' <span class=\"small\" style=\"font-weight:400;color:var(--muted);\">('+esc(p.pupilClass||'unassigned')+')</span></span>' +",
"      '<span class=\"small\">'+p.attempts+' tries</span>' +",
"      '<span class=\"pill\" style=\"margin-left:10px;\">Best '+p.bestScore+'</span></div>';",
"  }).join('');",
"  if(!rows) rows = '<p class=\"small\">No scores yet &mdash; be the first to complete a topic!</p>';",
"  return '<div class=\"card\"><h2 style=\"margin-top:0;\">Leaderboard</h2>'+rows+'</div>';",
"}"
];

var TEACHER_JS = [
"var SUBS_PAGE_SIZE = 50;",
"function submissionsQueryString(){",
"  var qp = ['limit='+SUBS_PAGE_SIZE, 'offset='+state.subsOffset];",
"  if(state.subsFilterClass) qp.push('class='+encodeURIComponent(state.subsFilterClass));",
"  if(state.subsFilterTopic) qp.push('topic='+encodeURIComponent(state.subsFilterTopic));",
"  if(state.subsSort && state.subsSort!=='newest') qp.push('sort='+encodeURIComponent(state.subsSort));",
"  if(state.subsArchivedView && state.subsArchivedView!=='active') qp.push('archived='+encodeURIComponent(state.subsArchivedView));",
"  return qp.join('&');",
"}",
"function loadTeacherSubmissions(reset){",
"  if(reset){ state.teacherSubs = []; state.subsOffset = 0; state.selectedSubs = {}; }",
"  state.subsLoading = true; render();",
"  apiGet('/api/teacher/submissions?'+submissionsQueryString()).then(function(res){",
"    state.subsLoading = false;",
"    if(res.ok){",
"      state.teacherSubs = state.teacherSubs.concat(res.data.submissions);",
"      state.subsOffset = state.teacherSubs.length;",
"      state.subsTotal = res.data.total;",
"      state.subsHasMore = res.data.hasMore;",
"    }",
"    render();",
"  });",
"}",
"function loadTeacherRubric(){",
"  apiGet('/api/teacher/rubric').then(function(res){",
"    if(res.ok){ state.rubricText = res.data.rubric; state.rubricIsDefault = res.data.isDefault; render(); }",
"  });",
"}",
"function loadTeacherModelGroq(){",
"  apiGet('/api/teacher/model-groq').then(function(res){",
"    if(res.ok){ state.groqModel = res.data.model; state.groqModelIsDefault = res.data.isDefault; state.groqModelOptions = res.data.options || []; render(); }",
"  });",
"}",
"function loadTeacherPupils(){",
"  var q = state.pupilsFilterClass ? ('?class='+encodeURIComponent(state.pupilsFilterClass)) : '';",
"  apiGet('/api/teacher/pupils'+q).then(function(res){",
"    if(res.ok){ state.pupilsList = res.data.pupils; render(); }",
"  });",
"}",
"function loadTeacherClasses(){",
"  apiGet('/api/teacher/classes').then(function(res){",
"    if(res.ok){ state.classesList = res.data.classes || []; render(); }",
"  });",
"}",
"function loadTeacherAdmins(){",
"  apiGet('/api/admin/teachers').then(function(res){",
"    if(res.ok){ state.adminTeachers = res.data.teachers; render(); }",
"  });",
"}",
"function loadPupilDetail(name, pupilClass){",
"  state.teacherPupilView = 'loading';",
"  apiGet('/api/teacher/pupil?name='+encodeURIComponent(name)+'&class='+encodeURIComponent(pupilClass)).then(function(res){",
"    if(res.ok){ state.teacherPupilView = res.data; } else { state.teacherPupilView = null; state.error = res.data.error||'Could not load pupil.'; }",
"    render();",
"  });",
"}",
"",
"function teacherHtml(){",
"  if(!state.isSuperAdmin && ['topics','settings','admins'].indexOf(state.teacherTab)!==-1) state.teacherTab='leaderboard';",
"  var html = '<div class=\"tabs\">' +",
"    tTab('leaderboard','Leaderboard') + tTab('submissions','Submissions') + tTab('pupils','Pupils') +",
"    (state.isSuperAdmin ? (tTab('topics','Topics') + tTab('settings','Settings') + tTab('admins','Admins')) : '') +",
"    '</div>';",
"  if(state.teacherTab==='leaderboard') html += teacherLeaderboardHtml();",
"  else if(state.teacherTab==='submissions') html += teacherSubmissionsHtml();",
"  else if(state.teacherTab==='topics' && state.isSuperAdmin) html += teacherTopicsHtml();",
"  else if(state.teacherTab==='pupils') html += teacherPupilsHtml();",
"  else if(state.teacherTab==='settings' && state.isSuperAdmin) html += teacherSettingsHtml();",
"  else if(state.teacherTab==='admins' && state.isSuperAdmin) html += teacherAdminsHtml();",
"  return html;",
"}",
"",
"function tTab(id,label){",
"  var active = state.teacherTab===id ? ' active' : '';",
"  return '<div class=\"tab'+active+'\" data-action=\"teacher-tab\" data-tab=\"'+id+'\">'+esc(label)+'</div>';",
"}",
"",
"function teacherLeaderboardHtml(){",
"  var rows = state.leaderboard.map(function(p,i){",
"    return '<div class=\"board-row\"><span class=\"rank\">#'+(i+1)+'</span>' +",
"      '<span style=\"flex:1;padding:0 10px;font-weight:700;\">'+esc(p.name)+' <span class=\"small\" style=\"font-weight:400;color:var(--muted);\">('+esc(p.pupilClass||'unassigned')+')</span></span>' +",
"      '<span class=\"small\">'+p.attempts+' tries &middot; total '+p.totalScore+'</span>' +",
"      '<span class=\"pill\" style=\"margin:0 10px;\">Best '+p.bestScore+'</span>' +",
"      '<button class=\"btn-ghost btn-small\" data-action=\"view-pupil\" data-name=\"'+esc(p.name)+'\" data-class=\"'+esc(p.pupilClass||'unassigned')+'\">Progress</button>' +",
"      '<button class=\"btn-danger\" data-action=\"reset-pupil\" data-name=\"'+esc(p.name)+'\" data-class=\"'+esc(p.pupilClass||'unassigned')+'\">Reset</button></div>';",
"  }).join('');",
"  if(!rows) rows = '<p class=\"small\">No scores yet.</p>';",
"  var classOpts = '<option value=\"\">All classes</option>' + (state.classesList||[]).map(function(c){",
"    return '<option value=\"'+esc(c)+'\"'+(state.lbFilterClass===c?' selected':'')+'>'+esc(c)+'</option>';",
"  }).join('');",
"  var filterBar = '<div class=\"row\" style=\"margin-bottom:10px;\"><label style=\"margin:0;\">Class</label><select id=\"lbClassFilter\">'+classOpts+'</select></div>';",
"  return '<div class=\"card\"><div class=\"flex-between\"><h2 style=\"margin-top:0;\">Leaderboard</h2>' +",
"    '<button class=\"btn-danger\" data-action=\"reset-all\">Reset Entire Leaderboard</button></div>' + filterBar + rows + '</div>';",
"}",
"",
"function teacherPupilsHtml(){",
"  if(state.teacherPupilView === 'loading'){ return '<div class=\"card\"><p class=\"small\">Loading pupil...</p></div>'; }",
"  if(state.teacherPupilView){ return teacherPupilDetailHtml(state.teacherPupilView); }",
"  if(!state.pupilsList){ return '<div class=\"card\"><p class=\"small\">Loading pupils...</p></div>'; }",
"  var classOpts = '<option value=\"\">All classes</option>' + (state.classesList||[]).map(function(c){",
"    return '<option value=\"'+esc(c)+'\"'+(state.pupilsFilterClass===c?' selected':'')+'>'+esc(c)+'</option>';",
"  }).join('');",
"  var filterBar = '<div class=\"row\" style=\"margin-bottom:10px;\"><label style=\"margin:0;\">Class</label><select id=\"pupilsClassFilter\">'+classOpts+'</select></div>';",
"  var lastClass = null;",
"  var rows = state.pupilsList.map(function(p){",
"    var header = '';",
"    var cls = p.pupilClass || 'unassigned';",
"    if(cls !== lastClass){ header = '<h3 style=\"margin:14px 0 4px;\">'+esc(cls)+'</h3>'; lastClass = cls; }",
"    return header + '<div class=\"board-row\">' +",
"      '<span style=\"flex:1;padding:0 10px;font-weight:700;\">'+esc(p.name)+' <span class=\"small\" style=\"font-weight:400;color:var(--muted);\">('+esc(p.pupilClass||'unassigned')+')</span></span>' +",
"      '<span class=\"small\">'+p.attempts+' tries</span>' +",
"      '<span class=\"pill\" style=\"margin:0 10px;\">Best '+p.bestScore+'</span>' +",
"      '<button class=\"btn-ghost btn-small\" data-action=\"view-pupil\" data-name=\"'+esc(p.name)+'\" data-class=\"'+esc(p.pupilClass||'unassigned')+'\">View Progress</button></div>';",
"  }).join('');",
"  if(!rows) rows = '<p class=\"small\">No pupils have submitted a scored attempt yet.</p>';",
"  return '<div class=\"card\"><h2 style=\"margin-top:0;\">Pupils</h2><p class=\"small\">Progress, strengths and areas to grow are based only on non-practice attempts that were fully AI-marked (not offline-fallback marked).</p>'+filterBar+rows+'</div>';",
"}",
"function scoreBarHtml(entry){",
"  var pct = Math.max(4, Math.round((entry.finalScore / (entry.maxScore||25)) * 100));",
"  return '<div class=\"small\" style=\"display:flex;align-items:center;gap:8px;margin-bottom:4px;\">' +",
"    '<span style=\"width:90px;color:var(--muted);\">'+esc(new Date(entry.timestamp).toLocaleDateString())+'</span>' +",
"    '<div style=\"flex:1;background:#eef2ee;border-radius:6px;overflow:hidden;height:14px;\"><div style=\"width:'+pct+'%;background:var(--forest);height:100%;\"></div></div>' +",
"    '<span style=\"width:60px;text-align:right;\">'+entry.finalScore+'/'+entry.maxScore+'</span>' +",
"    '</div>';",
"}",
"function teacherPupilDetailHtml(v){",
"  var p = v.pupil;",
"  var history = v.history || [];",
"  var trendRows = history.slice(-10).map(scoreBarHtml).join('');",
"  var recentRows = history.slice(-10).slice().reverse().map(function(h){",
"    return '<div class=\"breakdown-row\"><span>'+esc(h.topicTitle)+' <span class=\"small\" style=\"color:var(--muted);\">('+esc(new Date(h.timestamp).toLocaleDateString())+')</span></span><span>'+h.finalScore+'/'+h.maxScore+'</span></div>';",
"  }).join('');",
"  var strengthsHtml = (v.strengths||[]).length ? '<ul style=\"margin:4px 0 0 20px;\">'+v.strengths.map(function(s){return '<li>'+esc(s)+'</li>';}).join('')+'</ul>' : '<p class=\"small\">Not enough scored attempts yet.</p>';",
"  var concernsHtml = (v.concerns||[]).length ? '<ul style=\"margin:4px 0 0 20px;\">'+v.concerns.map(function(s){return '<li>'+esc(s)+'</li>';}).join('')+'</ul>' : '<p class=\"small\">Not enough scored attempts yet.</p>';",
"  return '<div class=\"card stack\">' +",
"    '<button class=\"btn-ghost btn-small\" data-action=\"back-to-pupils-list\" style=\"align-self:flex-start;\">&larr; All Pupils</button>' +",
"    '<h2 style=\"margin:0;\">'+esc(p.name)+' <span class=\"small\" style=\"font-weight:400;color:var(--muted);\">('+esc(p.pupilClass||'unassigned')+')</span></h2>' +",
"    '<div class=\"row\"><span class=\"pill\">Best '+p.bestScore+'</span><span class=\"small\">'+p.attempts+' scored attempts</span></div>' +",
"    '<div><h3 style=\"margin-bottom:4px;\">Score trend (most recent attempts, oldest to newest)</h3>' + (trendRows || '<p class=\"small\">No scored attempts yet.</p>') + '</div>' +",
"    '<div class=\"row\" style=\"align-items:flex-start;gap:20px;flex-wrap:wrap;\">' +",
"    '<div style=\"flex:1;min-width:200px;\"><h3 style=\"margin-bottom:4px;\">&#127775; Strengths</h3>'+strengthsHtml+'</div>' +",
"    '<div style=\"flex:1;min-width:200px;\"><h3 style=\"margin-bottom:4px;\">&#127793; Areas to grow</h3>'+concernsHtml+'</div>' +",
"    '</div>' +",
"    '<div><h3 style=\"margin-bottom:4px;\">Recent attempts</h3>'+(recentRows||'<p class=\"small\">None yet.</p>')+'</div>' +",
"    '</div>';",
"}",
"",
"function submissionsFilterBarHtml(){",
"  var classOpts = '<option value=\"\">All classes</option>' + (state.classesList||[]).map(function(c){",
"    return '<option value=\"'+esc(c)+'\"'+(state.subsFilterClass===c?' selected':'')+'>'+esc(c)+'</option>';",
"  }).join('');",
"  var topicTitles = []; (state.topics||[]).forEach(function(t){ if(topicTitles.indexOf(t.title)===-1) topicTitles.push(t.title); });",
"  var topicOpts = '<option value=\"\">All topics</option>' + topicTitles.map(function(t){",
"    return '<option value=\"'+esc(t)+'\"'+(state.subsFilterTopic===t?' selected':'')+'>'+esc(t)+'</option>';",
"  }).join('');",
"  var sortOpts = [['newest','Newest first'],['oldest','Oldest first'],['class','Class'],['topic','Topic'],['score_desc','Score (high to low)'],['score_asc','Score (low to high)']].map(function(o){",
"    return '<option value=\"'+o[0]+'\"'+(state.subsSort===o[0]?' selected':'')+'>'+esc(o[1])+'</option>';",
"  }).join('');",
"  var archOpts = [['active','Active (not archived)'],['archived','Archived only'],['all','All']].map(function(o){",
"    return '<option value=\"'+o[0]+'\"'+(state.subsArchivedView===o[0]?' selected':'')+'>'+esc(o[1])+'</option>';",
"  }).join('');",
"  return '<div class=\"row\" style=\"margin-bottom:10px;flex-wrap:wrap;gap:10px;\">' +",
"    '<div><label style=\"margin:0;\">Class</label><select id=\"subsClassFilter\">'+classOpts+'</select></div>' +",
"    '<div><label style=\"margin:0;\">Topic</label><select id=\"subsTopicFilter\">'+topicOpts+'</select></div>' +",
"    '<div><label style=\"margin:0;\">Sort by</label><select id=\"subsSortSelect\">'+sortOpts+'</select></div>' +",
"    '<div><label style=\"margin:0;\">Show</label><select id=\"subsArchivedSelect\">'+archOpts+'</select></div>' +",
"    '</div>';",
"}",
"function teacherSubmissionsHtml(){",
"  var selectedIds = Object.keys(state.selectedSubs).filter(function(id){return state.selectedSubs[id];});",
"  var selectedCount = selectedIds.length;",
"  var allChecked = state.teacherSubs.length>0 && state.teacherSubs.every(function(s){return !!state.selectedSubs[s.id];});",
"  var rows = state.teacherSubs.map(function(s){",
"    var flag = s.flagged ? '<span class=\"tag\" style=\"background:#fdecec;color:#b23a3a;\">filtered</span>' : '';",
"    var practiceTag = s.practice ? '<span class=\"tag\" style=\"background:#fff4e9;color:#8a5a0a;\">practice</span>' : '';",
"    var degradedTag = (s.gradingDegraded && !s.practice) ? '<span class=\"tag\" style=\"background:#fff4e9;color:#8a5a0a;\">not on leaderboard - offline marked</span>' : '';",
"    var archivedTag = s.archived ? '<span class=\"tag\" style=\"background:#eef2ee;color:var(--muted);\">archived</span>' : '';",
"    var modeTag = '<span class=\"tag\">'+(s.mode==='single'?'single field':'TREES branches')+'</span>';",
"    var checked = state.selectedSubs[s.id] ? ' checked' : '';",
"    return '<tr>' +",
"      '<td><input type=\"checkbox\" data-action=\"select-sub\" data-id=\"'+esc(s.id)+'\"'+checked+'/></td>' +",
"      '<td>'+esc(s.pupilName)+' <span class=\"small\" style=\"color:var(--muted);\">('+esc(s.pupilClass||'unassigned')+')</span></td>' +",
"      '<td>'+esc(s.topicTitle)+'<br/>'+modeTag+'</td>' +",
"      '<td>'+s.finalScore+' / '+s.maxScore+' '+flag+' '+practiceTag+' '+degradedTag+' '+archivedTag+'</td>' +",
"      '<td class=\"small\">'+new Date(s.createdAt).toLocaleString()+'</td>' +",
"      '<td><button class=\"btn-ghost btn-small\" data-action=\"view-submission\" data-id=\"'+esc(s.id)+'\">View</button> ' +",
"      '<button class=\"btn-ghost btn-small\" data-action=\"toggle-archive-submission\" data-id=\"'+esc(s.id)+'\" data-archived=\"'+(s.archived?'1':'0')+'\">'+(s.archived?'Unarchive':'Archive')+'</button> ' +",
"      '<button class=\"btn-danger\" data-action=\"delete-submission\" data-id=\"'+esc(s.id)+'\">Delete</button></td>' +",
"      '</tr>';",
"  }).join('');",
"  var table = '<table class=\"teacher-table\"><thead><tr><th><input type=\"checkbox\" data-action=\"select-all-subs\"'+(allChecked?' checked':'')+'/></th><th>Pupil</th><th>Topic</th><th>Final Score</th><th>When</th><th></th></tr></thead><tbody>'+rows+'</tbody></table>';",
"  if(!state.teacherSubs.length) table = state.subsLoading ? '<p class=\"small\">Loading&hellip;</p>' : '<p class=\"small\">No submissions match this view.</p>';",
"  var loadMore = '';",
"  if(state.teacherSubs.length){",
"    loadMore = '<div class=\"row\" style=\"margin-top:10px;align-items:center;\"><span class=\"small\">Showing '+state.teacherSubs.length+' of '+state.subsTotal+'</span>' +",
"      (state.subsHasMore ? '<button class=\"btn-ghost btn-small\" data-action=\"load-more-submissions\"'+(state.subsLoading?' disabled':'')+'>'+(state.subsLoading?'Loading...':'Load more')+'</button>' : '') +",
"      '</div>';",
"  }",
"  var bulkBar = '';",
"  if(selectedCount>0){",
"    var showingArchived = state.subsArchivedView==='archived';",
"    bulkBar = '<div class=\"row\" style=\"margin:10px 0;align-items:center;background:#fbfdf9;border:1px solid var(--line);border-radius:10px;padding:8px 12px;\">' +",
"      '<span class=\"small\" style=\"font-weight:700;\">'+selectedCount+' selected</span>' +",
"      (showingArchived",
"        ? '<button class=\"btn-ghost btn-small\" data-action=\"unarchive-selected\">Unarchive Selected</button>'",
"        : '<button class=\"btn-ghost btn-small\" data-action=\"archive-selected\">Archive Selected</button>') +",
"      '<button class=\"btn-danger btn-small\" data-action=\"delete-selected\">Delete Selected</button>' +",
"      '</div>';",
"  }",
"  var detail = '';",
"  if(state.viewingSubmission){",
"    var s = state.teacherSubs.filter(function(x){return x.id===state.viewingSubmission;})[0];",
"    if(s){",
"      var roundsHtml = (s.rounds||[]).map(function(rd,i){",
"        var answerHtml = rd.mode==='single'",
"          ? '<div class=\"breakdown-row\" style=\"flex-direction:column;align-items:flex-start;\"><strong>Answer</strong><span>'+esc((rd.answer&&rd.answer.text)||'')+'</span></div>'",
"          : Object.keys((rd.answer&&rd.answer.parts)||{}).map(function(k){",
"              return '<div class=\"breakdown-row\" style=\"flex-direction:column;align-items:flex-start;\"><strong>'+esc(k)+'</strong><span>'+esc(rd.answer.parts[k])+'</span></div>';",
"            }).join('');",
"        return '<div class=\"card\" style=\"margin-top:12px;background:#fbfdf9;\">' +",
"          '<div class=\"flex-between\"><h4 style=\"margin:0;\">Question '+(i+1)+' &mdash; '+rd.score+'/'+rd.max+'</h4><div class=\"row\" style=\"gap:6px;\">'+aiStatusTag(rd.markedBy)+coachUsedTag(rd.coachUsed)+'</div></div>' +",
"          '<p class=\"small\" style=\"font-weight:700;\">'+esc(rd.question)+'</p>' +",
"          '<div class=\"feedback-box\" style=\"margin:8px 0;\">'+esc(rd.feedback)+'</div>' +",
"          '<div>'+breakdownHtml(rd.breakdown)+'</div>' +",
"          (rd.modelAnswer ? '<div class=\"coach-panel\" style=\"margin-top:8px;\"><div class=\"small\" style=\"font-weight:800;margin-bottom:4px;\">&#10024; AI model answer shown to pupil</div><p class=\"small\" style=\"margin:0;\">'+esc(rd.modelAnswer)+'</p></div>' : '') +",
"          '<div style=\"height:8px;\"></div>' + answerHtml +",
"          '</div>';",
"      }).join('');",
"      detail = '<div class=\"card\" id=\"submissionDetail\" style=\"margin-top:16px;\"><div class=\"flex-between\"><h3 style=\"margin:0;\">'+esc(s.pupilName)+' ('+esc(s.pupilClass||'unassigned')+') &mdash; '+esc(s.topicTitle)+' ('+s.finalScore+'/'+s.maxScore+')</h3>' +",
"        '<button class=\"btn-ghost btn-small\" data-action=\"close-submission\">Close</button></div>' +",
"        '<p class=\"small\">Final score is the average of the 3 questions below. Mode: '+esc(s.mode==='single'?'single response box':'separated TREES branches')+'</p>' +",
"        roundsHtml + '</div>';",
"    }",
"  }",
"  return '<div class=\"card\"><div class=\"flex-between\"><h2 style=\"margin-top:0;\">Submissions</h2>' +",
"    '<button class=\"btn-gold btn-small\" data-action=\"export-csv\">Export CSV &#11015;&#65039;</button></div>' + submissionsFilterBarHtml() + bulkBar + table + loadMore + '</div>' + detail;",
"}",
"",
"function teacherTopicsHtml(){",
"  var rows = state.topics.map(function(t){",
"    return '<div class=\"topic-card\" style=\"cursor:default;\">' +",
"      (t.imageUrl ? '<img src=\"'+esc(t.imageUrl)+'\" alt=\"\"/>' : '') +",
"      '<div class=\"tc-body\"><h3>'+esc(t.title)+'</h3>' +",
"      '<div class=\"small\">'+(t.questions||[]).map(esc).join(' &middot; ')+'</div>' +",
"      '<div class=\"row\" style=\"margin-top:8px;\">' +",
"      '<button class=\"btn-ghost btn-small\" data-action=\"edit-topic\" data-id=\"'+esc(t.id)+'\">Edit</button>' +",
"      '<button class=\"btn-danger\" data-action=\"delete-topic\" data-id=\"'+esc(t.id)+'\">Delete</button>' +",
"      '</div></div></div>';",
"  }).join('');",
"  var edit = state.editingTopic || {};",
"  var q = edit.questions || ['','',''];",
"  var coach = edit.coach || [{starters:[],resources:[]},{starters:[],resources:[]},{starters:[],resources:[]}];",
"  function coachGroupHtml(qi){",
"    var c = coach[qi] || {starters:[],resources:[]};",
"    var res = (c.resources||[]).concat([{},{}]).slice(0,2);",
"    var resFields = res.map(function(r,ri){",
"      var typeSel = '<select id=\"tf_coach'+qi+'_res'+ri+'_type\">' +",
"        '<option value=\"article\"'+(r.type!=='video'?' selected':'')+'>Article</option>' +",
"        '<option value=\"video\"'+(r.type==='video'?' selected':'')+'>Video (YouTube link plays locked to just this video)</option>' +",
"        '</select>';",
"      return '<div class=\"row\" style=\"align-items:flex-end;\">' +",
"        '<div style=\"flex:1;min-width:140px;\"><label>Resource '+(ri+1)+' title</label><input type=\"text\" id=\"tf_coach'+qi+'_res'+ri+'_title\" value=\"'+esc(r.title||'')+'\" placeholder=\"e.g. Earth Hour - Oral Topic\"/></div>' +",
"        '<div style=\"flex:1;min-width:140px;\"><label>Link</label><input type=\"text\" id=\"tf_coach'+qi+'_res'+ri+'_url\" value=\"'+esc(r.url||'')+'\" placeholder=\"https://...\"/></div>' +",
"        '<div style=\"min-width:120px;\"><label>Type</label>'+typeSel+'</div>' +",
"        '</div>';",
"    }).join('');",
"    return '<div class=\"coach-field-group stack\">' +",
"      '<div><label>Coach sentence starters for this question (one per line)</label>' +",
"      '<textarea id=\"tf_coach'+qi+'_starters\" placeholder=\"In the picture, I can see...\">'+esc((c.starters||[]).join('\\n'))+'</textarea>' +",
"      '<div class=\"hint\">Shown to pupils only if they tap \\'Ask the Coach\\' - this is quietly flagged on your end, pupils are not told.</div></div>' +",
"      resFields +",
"      '<p class=\"hint\">Paste real article or video links yourself - this app does not auto-generate or verify links.</p>' +",
"      '</div>';",
"  }",
"  var form = '<div class=\"card stack\" style=\"margin-top:16px;\">' +",
"    '<h3 style=\"margin:0;\">'+(edit.id?'Edit Topic':'Add New Picture / Topic')+'</h3>' +",
"    '<p class=\"small\">All 3 questions below are used as separate graded rounds - pupils answer all 3 in one sitting and their final score is the average. Please fill in all 3.</p>' +",
"    '<div><label>Title</label><input type=\"text\" id=\"tf_title\" value=\"'+esc(edit.title||'')+'\" placeholder=\"e.g. Recycling at Home\"/></div>' +",
"    '<div><label>Picture URL</label><input type=\"text\" id=\"tf_image\" value=\"'+esc(edit.imageUrl||'')+'\" placeholder=\"https://...\"/><div class=\"hint\">Paste a direct image link (jpg/png). This is the stimulus picture pupils see.</div></div>' +",
"    '<div><label>Picture Description (for AI marking, optional but recommended)</label>' +",
"    '<textarea id=\"tf_imageDesc\" placeholder=\"e.g. A boy and his grandmother sorting plastic bottles into a blue recycling bin at a void deck.\">'+esc(edit.imageDescription||'')+'</textarea>' +",
"    '<div class=\"hint\">If the AI marker cannot fetch or see the picture itself, it falls back to this description to judge the Evidence part accurately. Describe what is actually in the picture, not the topic in general.</div></div>' +",
"    '<div><label>Question 1 (what is happening)</label><input type=\"text\" id=\"tf_q1\" value=\"'+esc(q[0]||'')+'\"/></div>' +",
"    coachGroupHtml(0) +",
"    '<div><label>Question 2 (why / opinion)</label><input type=\"text\" id=\"tf_q2\" value=\"'+esc(q[1]||'')+'\"/></div>' +",
"    coachGroupHtml(1) +",
"    '<div><label>Question 3 (personal experience)</label><input type=\"text\" id=\"tf_q3\" value=\"'+esc(q[2]||'')+'\"/></div>' +",
"    coachGroupHtml(2) +",
"    '<div><label>Tags (comma separated)</label><input type=\"text\" id=\"tf_tags\" value=\"'+esc((edit.tags||[]).join(', '))+'\"/></div>' +",
"    '<div class=\"row\">' +",
"    '<button class=\"btn-primary\" data-action=\"save-topic\" data-id=\"'+esc(edit.id||'')+'\">'+(edit.id?'Save Changes':'Add Topic')+'</button>' +",
"    (edit.id ? '<button class=\"btn-ghost\" data-action=\"cancel-edit-topic\">Cancel</button>' : '') +",
"    '</div></div>';",
"  return '<div class=\"card\"><h2 style=\"margin-top:0;\">Topics &amp; Pictures</h2><div class=\"topic-grid\">'+rows+'</div></div>' + form;",
"}",
"",
"function teacherSettingsHtml(){",
"  var rubricNote = state.rubricIsDefault ? '<span class=\"tag\">using built-in default</span>' : '<span class=\"tag\" style=\"background:var(--sky);\">custom rubric active</span>';",
"  var modelNote = state.groqModelIsDefault ? '<span class=\"tag\">using built-in default</span>' : '<span class=\"tag\" style=\"background:var(--sky);\">custom model active</span>';",
"  var knownIds = (state.groqModelOptions||[]).map(function(o){return o.id;});",
"  var isKnownModel = knownIds.indexOf(state.groqModel) !== -1;",
"  var modelOptionsHtml = (state.groqModelOptions||[]).map(function(o){",
"    return '<option value=\"'+esc(o.id)+'\"'+(state.groqModel===o.id?' selected':'')+'>'+esc(o.label)+'</option>';",
"  }).join('') + '<option value=\"__custom__\"'+(isKnownModel?'':' selected')+'>Other (type model ID below)</option>';",
"  return '<div class=\"card stack\">' +",
"    '<h2 style=\"margin-top:0;\">Settings</h2>' +",
"    '<div><label>New Teacher Password</label><input type=\"password\" id=\"newPw\" placeholder=\"At least 6 characters\"/></div>' +",
"    '<button class=\"btn-primary\" data-action=\"change-password\">Update Password</button>' +",
"    '<p class=\"hint\">This password is stored in D1 (config table), not in the source code. This is only palpatine\\'s password - teacher-admin passwords are managed separately, in the Admins tab.</p>' +",
"    '<hr style=\"border:none;border-top:1px solid var(--line);margin:8px 0;\"/>' +",
"    '<div class=\"flex-between\"><label style=\"margin:0;\">AI Marking Rubric</label>'+rubricNote+'</div>' +",
"    '<p class=\"hint\">This text is sent to the AI marker with every submission and controls how strictly/leniently each TREES part is scored. Leave blank and save to reset to the built-in default.</p>' +",
"    '<textarea id=\"rubricText\" style=\"min-height:220px;font-family:monospace;font-size:13px;\">'+esc(state.rubricText)+'</textarea>' +",
"    '<div class=\"row\">' +",
"    '<button class=\"btn-primary\" data-action=\"save-rubric\">Save Rubric</button>' +",
"    '<button class=\"btn-ghost\" data-action=\"reset-rubric\">Reset to Default</button>' +",
"    '</div>' +",
"    '<hr style=\"border:none;border-top:1px solid var(--line);margin:8px 0;\"/>' +",
"    '<div class=\"flex-between\"><label style=\"margin:0;\">Groq Marking Model</label>'+modelNote+'</div>' +",
"    '<p class=\"hint\">This is the 2nd AI marker tried for every question, after Gemini (falls back to Workers AI, then an offline scorer if it also fails). Pick a known model, or choose \\'Other\\' to type any valid Groq model ID.</p>' +",
"    '<select id=\"groqModelSelect\">'+modelOptionsHtml+'</select>' +",
"    '<input id=\"groqModelCustom\" placeholder=\"e.g. openai/gpt-oss-120b\" style=\"'+(isKnownModel?'display:none;':'')+'margin-top:8px;\" value=\"'+(isKnownModel?'':esc(state.groqModel))+'\"/>' +",
"    '<div class=\"row\">' +",
"    '<button class=\"btn-primary\" data-action=\"save-groq-model\">Save Model</button>' +",
"    '<button class=\"btn-ghost\" data-action=\"reset-groq-model\">Reset to Default</button>' +",
"    '</div>' +",
"    '</div>';",
"}",
"",
"function teacherAdminsHtml(){",
"  if(!state.adminTeachers){ return '<div class=\"card\"><p class=\"small\">Loading teacher admins...</p></div>'; }",
"  var edit = state.editingTeacherAdmin;",
"  var rows = state.adminTeachers.map(function(t){",
"    return '<div class=\"board-row\">' +",
"      '<span style=\"flex:1;padding:0 10px;font-weight:700;\">'+esc(t.username)+'</span>' +",
"      '<span class=\"small\" style=\"flex:1;\">'+esc((t.classes||[]).join(', '))+'</span>' +",
"      '<button class=\"btn-ghost btn-small\" data-action=\"edit-teacher-admin\" data-username=\"'+esc(t.username)+'\">Edit</button>' +",
"      '<button class=\"btn-danger\" data-action=\"delete-teacher-admin\" data-username=\"'+esc(t.username)+'\">Remove</button></div>';",
"  }).join('');",
"  if(!rows) rows = '<p class=\"small\">No teacher-admin accounts yet.</p>';",
"  var isEditing = edit && edit.username;",
"  var form = '<div class=\"card stack\" style=\"margin-top:16px;\">' +",
"    '<h3 style=\"margin:0;\">'+(isEditing?'Edit '+esc(edit.username):'Add Teacher Admin')+'</h3>' +",
"    (isEditing ? '' : '<div><label>Username</label><input type=\"text\" id=\"ta_username\" placeholder=\"e.g. mrstan\" maxlength=\"30\"/><div class=\"hint\">Lowercase letters, numbers, - or _ only. This is what they type as their name to reach the teacher login.</div></div>') +",
"    '<div><label>'+(isEditing?'New Password (leave blank to keep current)':'Password')+'</label><input type=\"password\" id=\"ta_password\" placeholder=\"At least 6 characters\"/></div>' +",
"    '<div><label>Assigned Classes (comma separated)</label><input type=\"text\" id=\"ta_classes\" placeholder=\"e.g. 5IG, 5HP\" value=\"'+esc(edit&&edit.classes?edit.classes.join(', '):'')+'\"/><div class=\"hint\">They will only see pupils, submissions and the leaderboard for these classes. Topics and global Settings stay palpatine-only.</div></div>' +",
"    '<div class=\"row\">' +",
"    '<button class=\"btn-primary\" data-action=\"save-teacher-admin\" data-username=\"'+esc(isEditing?edit.username:'')+'\">'+(isEditing?'Save Changes':'Add Teacher Admin')+'</button>' +",
"    (isEditing ? '<button class=\"btn-ghost\" data-action=\"cancel-edit-teacher-admin\">Cancel</button>' : '') +",
"    '</div></div>';",
"  return '<div class=\"card\"><h2 style=\"margin-top:0;\">Teacher Admins</h2>' +",
"    '<p class=\"small\">Teacher admins can only view and administer pupils in their assigned classes - Leaderboard, Submissions and Pupils are scoped to those classes only. Only palpatine can manage Topics, Settings and this Admins tab.</p>' +",
"    rows + '</div>' + form;",
"}",
"",
"function teacherAdminsHtml(){",
"  if(!state.adminTeachers){ return '<div class=\"card\"><p class=\"small\">Loading teacher admins...</p></div>'; }",
"  var edit = state.editingTeacherAdmin;",
"  var rows = state.adminTeachers.map(function(t){",
"    return '<div class=\"board-row\">' +",
"      '<span style=\"flex:1;padding:0 10px;font-weight:700;\">'+esc(t.username)+'</span>' +",
"      '<span class=\"small\" style=\"flex:1;\">'+esc((t.classes||[]).join(', '))+'</span>' +",
"      '<button class=\"btn-ghost btn-small\" data-action=\"edit-teacher-admin\" data-username=\"'+esc(t.username)+'\">Edit</button>' +",
"      '<button class=\"btn-danger\" data-action=\"delete-teacher-admin\" data-username=\"'+esc(t.username)+'\">Remove</button></div>';",
"  }).join('');",
"  if(!rows) rows = '<p class=\"small\">No teacher-admin accounts yet.</p>';",
"  var isEditing = edit && edit.username;",
"  var form = '<div class=\"card stack\" style=\"margin-top:16px;\">' +",
"    '<h3 style=\"margin:0;\">'+(isEditing?'Edit '+esc(edit.username):'Add Teacher Admin')+'</h3>' +",
"    (isEditing ? '' : '<div><label>Username</label><input type=\"text\" id=\"ta_username\" placeholder=\"e.g. mrstan\" maxlength=\"30\"/><div class=\"hint\">Lowercase letters, numbers, - or _ only. This is what they type as their name to reach the teacher login.</div></div>') +",
"    '<div><label>'+(isEditing?'New Password (leave blank to keep current)':'Password')+'</label><input type=\"password\" id=\"ta_password\" placeholder=\"At least 6 characters\"/></div>' +",
"    '<div><label>Assigned Classes (comma separated)</label><input type=\"text\" id=\"ta_classes\" placeholder=\"e.g. 5IG, 5HP\" value=\"'+esc(edit&&edit.classes?edit.classes.join(', '):'')+'\"/><div class=\"hint\">They will only see pupils, submissions and the leaderboard for these classes. Topics and global Settings stay palpatine-only.</div></div>' +",
"    '<div class=\"row\">' +",
"    '<button class=\"btn-primary\" data-action=\"save-teacher-admin\" data-username=\"'+esc(isEditing?edit.username:'')+'\">'+(isEditing?'Save Changes':'Add Teacher Admin')+'</button>' +",
"    (isEditing ? '<button class=\"btn-ghost\" data-action=\"cancel-edit-teacher-admin\">Cancel</button>' : '') +",
"    '</div></div>';",
"  return '<div class=\"card\"><h2 style=\"margin-top:0;\">Teacher Admins</h2>' +",
"    '<p class=\"small\">Teacher admins can only view and administer pupils in their assigned classes - Leaderboard, Submissions and Pupils are scoped to those classes only. Only palpatine can manage Topics, Settings and this Admins tab.</p>' +",
"    rows + '</div>' + form;",
"}"
];

var EVENTS_JS = [
"function wireEvents(){",
"  var app = qs('#app');",
"  app.addEventListener('click', function(e){",
"    var target = e.target.closest('[data-action]');",
"    if(!target) return;",
"    var action = target.getAttribute('data-action');",
"    if(action==='login') doLogin();",
"    else if(action==='teacher-login') doTeacherLogin();",
"    else if(action==='cancel-teacher'){ state.pendingTeacherLogin=false; state.pendingTeacherUsername=''; state.error=''; render(); }",
"    else if(action==='logout'){ stopRecording(); doLogout(); }",
"    else if(action==='pupil-tab'){ stopRecording(); state.pupilTab = target.getAttribute('data-tab'); render(); }",
"    else if(action==='pupil-tab-lb'){ stopRecording(); state.lastResult=null; state.pupilTab='leaderboard'; render(); }",
"    else if(action==='pick-topic'){",
"      var id = target.getAttribute('data-id');",
"      state.currentTopic = state.topics.filter(function(t){return t.id===id;})[0] || null;",
"      state.practiceMode = false;",
"      state.coachOpen = [false,false,false]; state.coachUsed = [false,false,false];",
"      state.error=''; render();",
"    }",
"    else if(action==='back-to-topics'){ stopRecording(); state.currentTopic=null; state.lastResult=null; state.coachOpen=[false,false,false]; state.coachUsed=[false,false,false]; render(); }",
"    else if(action==='toggle-record'){",
"      var tid = target.getAttribute('data-target');",
"      if(state.recording === tid) stopRecording(); else startRecording(tid);",
"    }",
"    else if(action==='toggle-coach'){",
"      var ci = parseInt(target.getAttribute('data-round'),10);",
"      state.coachOpen[ci] = !state.coachOpen[ci];",
"      if(state.coachOpen[ci]) state.coachUsed[ci] = true;", // sticky - opening it once is enough to flag it, closing the panel doesn't un-flag it
"      render();",
"    }",
"    else if(action==='submit-response'){ stopRecording(); submitResponse(); }",
"    else if(action==='set-mode'){ stopRecording(); state.responseMode = target.getAttribute('data-mode'); render(); }",
"    else if(action==='play-again'){ stopRecording(); state.lastResult=null; state.currentTopic=null; state.practiceMode=false; state.coachOpen=[false,false,false]; state.coachUsed=[false,false,false]; render(); }",
"    else if(action==='teacher-tab'){",
"      state.teacherTab = target.getAttribute('data-tab');",
"      if(state.teacherTab==='submissions' && !state.teacherSubs.length) loadTeacherSubmissions(true);",
"      if(state.teacherTab==='settings') loadTeacherRubric();",
"      if(state.teacherTab==='settings') loadTeacherModelGroq();",
"      if(state.teacherTab==='pupils' && !state.pupilsList) loadTeacherPupils();",
"      if(state.teacherTab==='admins' && !state.adminTeachers) loadTeacherAdmins();",
"      render();",
"    }",
"    else if(action==='view-pupil'){",
"      var vpName = target.getAttribute('data-name');",
"      var vpClass = target.getAttribute('data-class');",
"      state.teacherTab = 'pupils';",
"      loadPupilDetail(vpName, vpClass);",
"      render();",
"    }",
"    else if(action==='back-to-pupils-list'){ state.teacherPupilView = null; render(); }",
"    else if(action==='reset-pupil'){",
"      var name = target.getAttribute('data-name');",
"      var cls = target.getAttribute('data-class') || 'unassigned';",
"      if(confirm('Reset leaderboard score and progress history for '+name+' ('+cls+')?')){",
"        apiSend('/api/teacher/leaderboard/reset','POST',{name:name, pupilClass:cls}).then(function(){ loadLeaderboard(); state.pupilsList=null; });",
"      }",
"    }",
"    else if(action==='reset-all'){",
"      if(confirm('Reset the ENTIRE leaderboard for all pupils? This cannot be undone.')){",
"        apiSend('/api/teacher/leaderboard/reset','POST',{}).then(function(){ loadLeaderboard(); state.pupilsList=null; });",
"      }",
"    }",
"    else if(action==='load-more-submissions'){ if(!state.subsLoading) loadTeacherSubmissions(false); }",
"    else if(action==='view-submission'){",
"      state.viewingSubmission = target.getAttribute('data-id'); render();",
"      setTimeout(function(){",
"        var el = document.getElementById('submissionDetail');",
"        if(el) el.scrollIntoView({behavior:'smooth', block:'start'});",
"      }, 0);",
"    }",
"    else if(action==='close-submission'){ state.viewingSubmission = null; render(); }",
"    else if(action==='delete-submission'){",
"      var sid = target.getAttribute('data-id');",
"      if(confirm('Delete this submission?')){",
"        apiSend('/api/teacher/submissions/'+sid,'DELETE',{}).then(function(){ loadTeacherSubmissions(true); loadLeaderboard(); });",
"      }",
"    }",
"    else if(action==='select-sub'){",
"      var selId = target.getAttribute('data-id');",
"      state.selectedSubs[selId] = target.checked;",
"      render();",
"    }",
"    else if(action==='select-all-subs'){",
"      var allSel = target.checked;",
"      state.teacherSubs.forEach(function(s){ state.selectedSubs[s.id] = allSel; });",
"      render();",
"    }",
"    else if(action==='toggle-archive-submission'){",
"      var taid = target.getAttribute('data-id');",
"      var wasArchived = target.getAttribute('data-archived')==='1';",
"      apiSend('/api/teacher/submissions/archive','POST',{ids:[taid], archived: !wasArchived}).then(function(){ loadTeacherSubmissions(true); });",
"    }",
"    else if(action==='archive-selected' || action==='unarchive-selected'){",
"      var ids = Object.keys(state.selectedSubs).filter(function(id){return state.selectedSubs[id];});",
"      if(!ids.length) return;",
"      apiSend('/api/teacher/submissions/archive','POST',{ids:ids, archived: action==='archive-selected'}).then(function(){",
"        state.selectedSubs = {}; loadTeacherSubmissions(true);",
"      });",
"    }",
"    else if(action==='delete-selected'){",
"      var delIds = Object.keys(state.selectedSubs).filter(function(id){return state.selectedSubs[id];});",
"      if(!delIds.length) return;",
"      if(!confirm('Delete '+delIds.length+' submission(s)? This cannot be undone.')) return;",
"      Promise.all(delIds.map(function(id){ return apiSend('/api/teacher/submissions/'+id,'DELETE',{}); })).then(function(){",
"        state.selectedSubs = {}; loadTeacherSubmissions(true); loadLeaderboard();",
"      });",
"    }",
"    else if(action==='edit-teacher-admin'){",
"      var euser = target.getAttribute('data-username');",
"      var existing = (state.adminTeachers||[]).filter(function(t){return t.username===euser;})[0];",
"      state.editingTeacherAdmin = existing ? Object.assign({}, existing) : { username: euser, classes: [] };",
"      render();",
"    }",
"    else if(action==='cancel-edit-teacher-admin'){ state.editingTeacherAdmin=null; render(); }",
"    else if(action==='delete-teacher-admin'){",
"      var duser = target.getAttribute('data-username');",
"      if(confirm('Remove teacher-admin \\''+duser+'\\'? They will no longer be able to log in.')){",
"        apiSend('/api/admin/teachers/'+encodeURIComponent(duser),'DELETE',{}).then(function(){ loadTeacherAdmins(); });",
"      }",
"    }",
"    else if(action==='save-teacher-admin'){",
"      var existingUsername = target.getAttribute('data-username');",
"      var classesArr = qsVal('ta_classes').split(',').map(function(s){return s.trim();}).filter(Boolean);",
"      var pw = qsVal('ta_password');",
"      if(!classesArr.length){ state.error='Assign at least one class.'; render(); return; }",
"      if(existingUsername){",
"        var body = { classes: classesArr };",
"        if(pw) body.newPassword = pw;",
"        apiSend('/api/admin/teachers/'+encodeURIComponent(existingUsername),'PUT',body).then(function(res){",
"          if(!res.ok){ state.error = res.data.error || 'Could not save.'; render(); return; }",
"          state.error=''; state.editingTeacherAdmin=null; loadTeacherAdmins();",
"        });",
"      } else {",
"        var uname = qsVal('ta_username').trim().toLowerCase();",
"        if(!uname){ state.error='Please enter a username.'; render(); return; }",
"        if(!pw || pw.length<6){ state.error='Password should be at least 6 characters.'; render(); return; }",
"        apiSend('/api/admin/teachers','POST',{username:uname, password:pw, classes:classesArr}).then(function(res){",
"          if(!res.ok){ state.error = res.data.error || 'Could not add teacher admin.'; render(); return; }",
"          state.error=''; state.editingTeacherAdmin=null; loadTeacherAdmins();",
"        });",
"      }",
"    }",
"    else if(action==='edit-topic'){",
"      var tid = target.getAttribute('data-id');",
"      var t = state.topics.filter(function(x){return x.id===tid;})[0];",
"      state.editingTopic = t ? Object.assign({}, t) : {};",
"      render();",
"    }",
"    else if(action==='cancel-edit-topic'){ state.editingTopic=null; render(); }",
"    else if(action==='delete-topic'){",
"      var did = target.getAttribute('data-id');",
"      if(confirm('Delete this topic?')){",
"        apiSend('/api/teacher/topics/'+did,'DELETE',{}).then(function(){ loadTopics(); });",
"      }",
"    }",
"    else if(action==='save-topic'){",
"      var coachPayload = [0,1,2].map(function(qi){",
"        var starters = qsVal('tf_coach'+qi+'_starters').split('\\n').map(function(s){return s.trim();}).filter(Boolean);",
"        var resources = [0,1].map(function(ri){",
"          var url = qsVal('tf_coach'+qi+'_res'+ri+'_url').trim();",
"          if(!url) return null;",
"          var title = qsVal('tf_coach'+qi+'_res'+ri+'_title').trim() || url;",
"          var typeEl = document.getElementById('tf_coach'+qi+'_res'+ri+'_type');",
"          var type = (typeEl && typeEl.value==='video') ? 'video' : 'article';",
"          return {title:title, url:url, type:type};",
"        }).filter(Boolean);",
"        return {starters:starters, resources:resources};",
"      });",
"      var payload = {",
"        id: target.getAttribute('data-id') || undefined,",
"        title: qsVal('tf_title'),",
"        imageUrl: qsVal('tf_image'),",
"        imageDescription: qsVal('tf_imageDesc'),",
"        questions: [qsVal('tf_q1'), qsVal('tf_q2'), qsVal('tf_q3')],",
"        tags: qsVal('tf_tags').split(',').map(function(s){return s.trim();}).filter(Boolean),",
"        coach: coachPayload",
"      };",
"      if(!payload.title){ state.error='Please give the topic a title.'; render(); return; }",
"      if(payload.questions.some(function(q){return !q || !q.trim();})){ state.error='Please fill in all 3 questions - each is used as a separate graded round.'; render(); return; }",
"      apiSend('/api/teacher/topics','POST',payload).then(function(res){",
"        if(!res.ok){ state.error = res.data.error || 'Could not save topic.'; render(); return; }",
"        state.editingTopic=null; state.error=''; loadTopics();",
"      });",
"    }",
"    else if(action==='change-password'){",
"      var pw = qsVal('newPw');",
"      apiSend('/api/teacher/password','POST',{newPassword:pw}).then(function(res){",
"        if(!res.ok){ state.error = res.data.error || 'Could not update password.'; render(); return; }",
"        state.error=''; alert('Password updated.'); render();",
"      });",
"    }",
"    else if(action==='export-csv'){",
"      fetch(API+'/api/teacher/submissions/export?'+submissionsQueryString(), { headers: authHeaders() }).then(function(r){ return r.text(); }).then(function(text){",
"        var blob = new Blob([text], {type:'text/csv;charset=utf-8;'});",
"        var url = URL.createObjectURL(blob);",
"        var a = document.createElement('a');",
"        a.href = url; a.download = 'just-a-chit-chat-submissions.csv';",
"        document.body.appendChild(a); a.click(); document.body.removeChild(a);",
"        URL.revokeObjectURL(url);",
"      });",
"    }",
"    else if(action==='save-rubric'){",
"      var rubricVal = qsVal('rubricText');",
"      apiSend('/api/teacher/rubric','POST',{rubric:rubricVal}).then(function(res){",
"        if(!res.ok){ state.error = res.data.error || 'Could not save rubric.'; render(); return; }",
"        state.rubricText = res.data.rubric; state.rubricIsDefault = res.data.isDefault; state.error='';",
"        alert('Rubric saved. It will be used for future AI-marked submissions.'); render();",
"      });",
"    }",
"    else if(action==='reset-rubric'){",
"      if(confirm('Reset the rubric back to the built-in default?')){",
"        apiSend('/api/teacher/rubric','POST',{rubric:''}).then(function(res){",
"          state.rubricText = res.data.rubric; state.rubricIsDefault = true; render();",
"        });",
"      }",
"    }",
"    else if(action==='save-groq-model'){",
"      var selectEl = document.getElementById('groqModelSelect');",
"      var modelVal = selectEl && selectEl.value==='__custom__' ? qsVal('groqModelCustom') : (selectEl ? selectEl.value : '');",
"      modelVal = (modelVal||'').trim();",
"      if(!modelVal){ state.error = 'Enter a model ID first.'; render(); return; }",
"      apiSend('/api/teacher/model-groq','POST',{model:modelVal}).then(function(res){",
"        if(!res.ok){ state.error = res.data.error || 'Could not save model.'; render(); return; }",
"        state.groqModel = res.data.model; state.groqModelIsDefault = res.data.isDefault; state.error='';",
"        alert('Groq model saved. It will be used for future AI-marked submissions.'); render();",
"      });",
"    }",
"    else if(action==='reset-groq-model'){",
"      if(confirm('Reset the Groq model back to the built-in default?')){",
"        apiSend('/api/teacher/model-groq','POST',{model:''}).then(function(res){",
"          state.groqModel = res.data.model; state.groqModelIsDefault = true; render();",
"        });",
"      }",
"    }",
"  });",
"",
"  app.addEventListener('change', function(e){",
"    if(e.target && e.target.getAttribute && e.target.getAttribute('data-action')==='toggle-practice'){",
"      state.practiceMode = e.target.checked;",
"    }",
"    else if(e.target && e.target.id==='groqModelSelect'){",
"      var customInput = document.getElementById('groqModelCustom');",
"      if(customInput) customInput.style.display = (e.target.value==='__custom__') ? '' : 'none';",
"    }",
"    else if(e.target && e.target.id==='subsClassFilter'){ state.subsFilterClass = e.target.value; loadTeacherSubmissions(true); }",
"    else if(e.target && e.target.id==='subsTopicFilter'){ state.subsFilterTopic = e.target.value; loadTeacherSubmissions(true); }",
"    else if(e.target && e.target.id==='subsSortSelect'){ state.subsSort = e.target.value; loadTeacherSubmissions(true); }",
"    else if(e.target && e.target.id==='subsArchivedSelect'){ state.subsArchivedView = e.target.value; loadTeacherSubmissions(true); }",
"    else if(e.target && e.target.id==='lbClassFilter'){ state.lbFilterClass = e.target.value; loadLeaderboard(); }",
"    else if(e.target && e.target.id==='pupilsClassFilter'){ state.pupilsFilterClass = e.target.value; loadTeacherPupils(); }",
"  });",
"",
"  app.addEventListener('input', function(e){",
"    if(e.target && e.target.getAttribute && e.target.getAttribute('data-action')==='part-input'){",
"      var round = e.target.getAttribute('data-round');",
"      var wrap = document.getElementById('treeProgress'+round);",
"      if(wrap) wrap.innerHTML = roundTreeProgressHtml(parseInt(round,10));",
"      var block = document.getElementById('block_'+e.target.id);",
"      if(block){",
"        if(e.target.value.trim()) block.classList.add('filled'); else block.classList.remove('filled');",
"      }",
"    }",
"  });",
"}",
"",
"function boot(){",
"  wireEvents();",
"  render();",
"}",
"document.addEventListener('DOMContentLoaded', boot);"
];

var SCRIPT_JS = APP_JS.concat(LOGIN_JS).concat(PUPIL_JS).concat(TEACHER_JS).concat(EVENTS_JS).join('\n');

var BODY_CLOSE = '\n</script>\n</body>\n</html>';

export var PAGE_HTML = HEAD + BODY_OPEN + SCRIPT_JS + BODY_CLOSE;
